name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  build-readme-file:
    runs-on: ubuntu-latest
    steps:
      # Checkout, install tools..
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run lint
      # Save files.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[ci skip] Automatic file changes/fix'
          branch: 'master'
          file_pattern: ':/*.*'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

  build-static-site:
    needs: build-readme-file
    runs-on: ubuntu-latest
    steps:
      # Checkout, install tools..
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # Setup Python for MkDocs
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      # Install Python dependencies and build static site
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Build MkDocs site
        run: |
          mkdocs build
      
      # Deploy to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: how-to-cook
          directory: site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
